/// Flutter icons ReportsIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReportsIcons
///      fonts:
///       - asset: fonts/ReportsIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ReportsIcons {
  ReportsIcons._();

  static const _kFontFam = 'ReportsIcons';
  static const String? _kFontPkg = null;

  static const IconData report =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_detailed =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
