name: reports
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  date_field: ^3.0.1
  easy_localization: ^3.0.0
  file_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_slidable: ^1.2.0
  flutter_speed_dial: ^6.0.0
  font_awesome_flutter: ^10.1.0
  logger: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.0.4
  path_provider: ^2.0.2
  provider: ^6.0.2
  share_plus: ^4.0.4
  shared_preferences: ^2.0.6

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  fonts:
    - family: ReportsIcons
      fonts:
        - asset: fonts/ReportsIcons.ttf
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/translations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
