name: reports
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_speed_dial: ^3.0.5
  date_field: ^2.0.1
  logger: ^1.0.0
  provider: ^5.0.0
  path_provider: ^2.0.2
  share_plus: ^2.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_slidable: ^0.6.0
  shared_preferences: ^2.0.6
  dropbox_client: ^0.8.0
  font_awesome_flutter: ^9.1.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.0.4
  file_picker: ^4.0.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: ReportsIcons
      fonts:
        - asset: fonts/ReportsIcons.ttf
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/translations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
