# Run build jobs in debug and release mode for each supported platform.
# As this is relatively time consuming, only run on the main branch and on pull requests

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  android-debug:
    name: Build Android Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
  android-release:
    name: Build Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
  ios-debug:
    name: Build iOS Debug
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --no-codesign
  ios-release:
    name: Build iOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --no-codesign --release
  macos-debug:
    name: Build MacOS Debug
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos
  macos-release:
    name: Build MacOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos --release
